# Generated by Django 3.1.4 on 2020-12-26 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20201226_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='0', max_length=64),
        ),
    ]
