# Generated by Django 3.1.2 on 2020-12-04 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20201124_2214'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
