# Generated by Django 3.1.2 on 2020-12-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
