# Generated by Django 3.1.2 on 2020-12-05 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_like_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='status',
        ),
    ]
